# COHORT ANALYSIS PROJECT

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("cleaned_online_retail.xlsx")

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-01-12 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-01-12 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34

In [4]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [6]:
df['InvoiceDate'].dtype

dtype('<M8[ns]')

# COHORT MONTH CREATION

In [7]:
df['CohortMonth'] = df.groupby('CustomerID')['InvoiceDate'].transform('min').dt.to_period('M')

In [8]:
df[['CustomerID','InvoiceDate','CohortMonth']].head()

   CustomerID         InvoiceDate CohortMonth
0       17850 2010-01-12 08:26:00     2010-01
1       17850 2010-01-12 08:26:00     2010-01
2       17850 2010-01-12 08:26:00     2010-01
3       17850 2010-01-12 08:26:00     2010-01
4       17850 2010-01-12 08:26:00     2010-01

In [9]:
df['CohortMonth'].nunique()

22

# INVOICE MONTH CREATION

In [10]:
df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')

In [11]:
df[['CustomerID','InvoiceDate','CohortMonth','InvoiceMonth']].head()

   CustomerID         InvoiceDate CohortMonth InvoiceMonth
0       17850 2010-01-12 08:26:00     2010-01      2010-01
1       17850 2010-01-12 08:26:00     2010-01      2010-01
2       17850 2010-01-12 08:26:00     2010-01      2010-01
3       17850 2010-01-12 08:26:00     2010-01      2010-01
4       17850 2010-01-12 08:26:00     2010-01      2010-01

In [12]:
df['InvoiceMonth'].nunique()

22