# DATA CLEANING

In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_excel("../data/online_retaildataset.xlsx")

In [10]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-01-12 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-01-12 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-01-12 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-01-12 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-01-12 08:26:00,3.39,17850.0,United Kingdom

# REMOVE MISSING CUSTOMER IDs

In [11]:
df.shape

(300000, 8)

In [12]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    300000 non-null  object
 1   StockCode    300000 non-null  object
 2   Description  298891 non-null  object
 3   Quantity     300000 non-null  int64
 4   InvoiceDate  300000 non-null  object
 5   UnitPrice    300000 non-null  float64
 6   CustomerID   215907 non-null  float64
 7   Country      300000 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 18.3+ MB

In [14]:
df.isnull().sum()

InvoiceNo          0
StockCode          0
Description     1109
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     84093
Country            0
dtype: int64

In [15]:
df = df.dropna(subset=['CustomerID'])

In [16]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [17]:
df.shape

(215907, 8)

# REMOVING CANCELLED TRANSACTIONS AND INVALID QUANTITIES

In [18]:
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

In [19]:
df.shape

(210716, 8)

In [20]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [21]:
df['Revenue'] = df['Quantity'] * df['UnitPrice']

In [22]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-01-12 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-01-12 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-01-12 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-01-12 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-01-12 08:26:00,3.39,17850.0,United Kingdom,20.34

In [23]:
df.shape

(210716, 9)

# CLEANED DATASET FOR COHORT ANALYSIS

In [25]:
df.to_excel("cleaned_online_retail.xlsx", index=False)