##Import Required Libraries

In [1]:
import pandas as pd

##Load Business KPI Dashboard

In [2]:
performance = pd.read_excel("Business_KPI_Dashboard.xlsx")
print("Business KPI Dashboard Loaded Successfully")
display(performance)

Business KPI Dashboard Loaded Successfully

,RegionSegment,Total_Customers,Total_Orders,Total_Revenue,Average_Order_Value,Purchase_Frequency,Historical_CLTV,Revenue_Rank,CLTV_Rank
0,Europe,186,615,462471.320,751.99,3.31,2489.09,3,2
1,Other,128,425,464744.970,1093.52,3.32,3630.49,2,1
2,UK,2908,9623,3959382.112,411.45,3.31,1361.90,1,3

##Rule-Based Recommendation Engine

In [3]:
def generate_recommendation(row):

    # Highest Revenue but not Highest CLTV
    if row["Revenue_Rank"] == 1 and row["CLTV_Rank"] != 1:

        recommendation = "Improve customer retention through loyalty programs."

        priority = "High"

        impact = "Increase repeat purchases and long-term customer value."

    # Highest CLTV but not Highest Revenue
    elif row["CLTV_Rank"] == 1 and row["Revenue_Rank"] != 1:

        recommendation = "Increase customer acquisition through targeted marketing."

        priority = "High"

        impact = "Acquire more high-value customers."

    # Lowest Revenue Region
    elif row["Revenue_Rank"] == performance["Revenue_Rank"].max():

        recommendation = "Launch promotional campaigns and regional offers."

        priority = "Medium"

        impact = "Improve regional revenue."

    # Lowest Purchase Frequency
    elif row["Purchase_Frequency"] == performance["Purchase_Frequency"].min():

        recommendation = "Introduce personalized engagement campaigns."

        priority = "Medium"

        impact = "Increase purchase frequency."

    else:

        recommendation = "Continue monitoring customer behavior and optimize business strategies."

        priority = "Low"

        impact = "Maintain consistent business performance."

    return pd.Series([recommendation, priority, impact])

##Apply Recommendation Engine

In [4]:
performance[
    ["Recommendation",
     "Priority",
     "Expected_Impact"]
] = performance.apply(
    generate_recommendation,
    axis=1
)

display(performance)

,RegionSegment,Total_Customers,Total_Orders,Total_Revenue,Average_Order_Value,Purchase_Frequency,Historical_CLTV,Revenue_Rank,CLTV_Rank,Recommendation,Priority,Expected_Impact
0,Europe,186,615,462471.320,751.99,3.31,2489.09,3,2,Launch promotional campaigns and regional offers.,Medium,Improve regional revenue.
1,Other,128,425,464744.970,1093.52,3.32,3630.49,2,1,Increase customer acquisition through targeted...,High,Acquire more high-value customers.
2,UK,2908,9623,3959382.112,411.45,3.31,1361.90,1,3,Improve customer retention through loyalty pro...,High,Increase repeat purchases and long-term custom...

## Business Decision Report

In [5]:
decision_report = performance[[
    "RegionSegment",
    "Total_Revenue",
    "Historical_CLTV",
    "Purchase_Frequency",
    "Recommendation",
    "Priority",
    "Expected_Impact"
]]

print("="*60)
print("BUSINESS DECISION REPORT")
print("="*60)

display(decision_report)

============================================================
BUSINESS DECISION REPORT
============================================================

,RegionSegment,Total_Revenue,Historical_CLTV,Purchase_Frequency,Recommendation,Priority,Expected_Impact
0,Europe,462471.320,2489.09,3.31,Launch promotional campaigns and regional offers.,Medium,Improve regional revenue.
1,Other,464744.970,3630.49,3.32,Increase customer acquisition through targeted...,High,Acquire more high-value customers.
2,UK,3959382.112,1361.90,3.31,Improve customer retention through loyalty pro...,High,Increase repeat purchases and long-term custom...

## High Priority Recommendations

In [6]:
high_priority = decision_report[
    decision_report["Priority"] == "High"
]

print("="*60)
print("HIGH PRIORITY BUSINESS ACTIONS")
print("="*60)

display(high_priority)

============================================================
HIGH PRIORITY BUSINESS ACTIONS
============================================================

,RegionSegment,Total_Revenue,Historical_CLTV,Purchase_Frequency,Recommendation,Priority,Expected_Impact
1,Other,464744.970,3630.49,3.32,Increase customer acquisition through targeted...,High,Acquire more high-value customers.
2,UK,3959382.112,1361.90,3.31,Improve customer retention through loyalty pro...,High,Increase repeat purchases and long-term custom...

##Business Summary

In [7]:
summary = pd.DataFrame({

    "Category":[
        "Highest Revenue Region",
        "Highest Historical CLTV Region",
        "Highest Priority Recommendations"
    ],

    "Result":[

        performance.loc[
            performance["Revenue_Rank"]==1,
            "RegionSegment"
        ].values[0],

        performance.loc[
            performance["CLTV_Rank"]==1,
            "RegionSegment"
        ].values[0],

        len(high_priority)

    ]

})

display(summary)

                           Category Result
0            Highest Revenue Region     UK
1    Highest Historical CLTV Region  Other
2  Highest Priority Recommendations      2

##Save Report

In [8]:
with pd.ExcelWriter("Business_Decision_Recommendations.xlsx") as writer:

    decision_report.to_excel(
        writer,
        sheet_name="Decision Report",
        index=False
    )

    high_priority.to_excel(
        writer,
        sheet_name="High Priority Actions",
        index=False
    )

    summary.to_excel(
        writer,
        sheet_name="Business Summary",
        index=False
    )

print("Business_Decision_Recommendations.xlsx saved successfully.")

Business_Decision_Recommendations.xlsx saved successfully.