##Import Required Libraries

In [ ]:
import pandas as pd

##Load Business KPI Dashboard

In [2]:
performance = pd.read_excel("Business_KPI_Dashboard.xlsx")
print("Dataset Loaded Successfully")
display(performance)

Dataset Loaded Successfully

,RegionSegment,Total_Customers,Total_Orders,Total_Revenue,Average_Order_Value,Purchase_Frequency,Historical_CLTV,Revenue_Rank,CLTV_Rank
0,Europe,186,615,462471.320,751.99,3.31,2489.09,3,2
1,Other,128,425,464744.970,1093.52,3.32,3630.49,2,1
2,UK,2908,9623,3959382.112,411.45,3.31,1361.90,1,3

##Identify Best and Worst Performing Regions

In [3]:
highest_revenue = performance.loc[performance["Total_Revenue"].idxmax()]
lowest_revenue = performance.loc[performance["Total_Revenue"].idxmin()]

highest_cltv = performance.loc[performance["Historical_CLTV"].idxmax()]
lowest_cltv = performance.loc[performance["Historical_CLTV"].idxmin()]

highest_aov = performance.loc[performance["Average_Order_Value"].idxmax()]
highest_pf = performance.loc[performance["Purchase_Frequency"].idxmax()]

##Executive Business Insights

In [4]:
print("="*60)
print("EXECUTIVE BUSINESS INSIGHTS")
print("="*60)

print(f"\n1. Highest Revenue Region")
print(f"Region : {highest_revenue['RegionSegment']}")
print(f"Revenue: {highest_revenue['Total_Revenue']:,.2f}")
print("Insight: This region contributes the highest share of total revenue.")

print("\n" + "-"*60)

print(f"\n2. Highest Historical CLTV Region")
print(f"Region : {highest_cltv['RegionSegment']}")
print(f"Historical CLTV: {highest_cltv['Historical_CLTV']:.2f}")
print("Insight: Customers from this region generate the highest long-term value.")

print("\n" + "-"*60)

print(f"\n3. Lowest Revenue Region")
print(f"Region : {lowest_revenue['RegionSegment']}")
print(f"Revenue: {lowest_revenue['Total_Revenue']:,.2f}")
print("Insight: This region requires improved customer acquisition and retention.")

print("\n" + "-"*60)

print(f"\n4. Highest Average Order Value")
print(f"Region : {highest_aov['RegionSegment']}")
print(f"AOV : {highest_aov['Average_Order_Value']:.2f}")

print("\n" + "-"*60)

print(f"\n5. Highest Purchase Frequency")
print(f"Region : {highest_pf['RegionSegment']}")
print(f"Purchase Frequency : {highest_pf['Purchase_Frequency']:.2f}")

============================================================
EXECUTIVE BUSINESS INSIGHTS
============================================================

1. Highest Revenue Region
Region : UK
Revenue: 3,959,382.11
Insight: This region contributes the highest share of total revenue.

------------------------------------------------------------

2. Highest Historical CLTV Region
Region : Other
Historical CLTV: 3630.49
Insight: Customers from this region generate the highest long-term value.

------------------------------------------------------------

3. Lowest Revenue Region
Region : Europe
Revenue: 462,471.32
Insight: This region requires improved customer acquisition and retention.

------------------------------------------------------------

4. Highest Average Order Value
Region : Other
AOV : 1093.52

------------------------------------------------------------

5. Highest Purchase Frequency
Region : Other
Purchase Frequency : 3.32

## Strategic Business Recommendations

In [5]:
recommendations = []
recommendations.append(
    f"Strengthen customer loyalty initiatives in {highest_revenue['RegionSegment']} to maintain high revenue."
)
recommendations.append(
    f"Increase marketing investment in {highest_cltv['RegionSegment']} because it generates the highest customer lifetime value."
)
recommendations.append(
    f"Launch customer engagement campaigns in {lowest_revenue['RegionSegment']} to improve sales performance."
)
recommendations.append(
    "Use customer segmentation for targeted marketing and personalized offers."
)
recommendations.append(
    "Monitor customer retention and CLTV regularly to support business decisions."
)
print("="*60)
print("STRATEGIC BUSINESS RECOMMENDATIONS")
print("="*60)

for i, rec in enumerate(recommendations, 1):
    print(f"{i}. {rec}")

============================================================
STRATEGIC BUSINESS RECOMMENDATIONS
============================================================
1. Strengthen customer loyalty initiatives in UK to maintain high revenue.
2. Increase marketing investment in Other because it generates the highest customer lifetime value.
3. Launch customer engagement campaigns in Europe to improve sales performance.
4. Use customer segmentation for targeted marketing and personalized offers.
5. Monitor customer retention and CLTV regularly to support business decisions.

##  Executive Summary

In [15]:
summary = pd.DataFrame({
    "Category": [
        "Highest Revenue Region",
        "Highest Historical CLTV",
        "Lowest Revenue Region",
        "Highest Average Order Value",
        "Highest Purchase Frequency"
    ],
    "Region": [
        highest_revenue["RegionSegment"],
        highest_cltv["RegionSegment"],
        lowest_revenue["RegionSegment"],
        highest_aov["RegionSegment"],
        highest_pf["RegionSegment"]
    ]
})

display(summary)

                      Category  Region
0       Highest Revenue Region      UK
1      Highest Historical CLTV   Other
2        Lowest Revenue Region  Europe
3  Highest Average Order Value   Other
4   Highest Purchase Frequency   Other

##Business Insights

In [9]:
insights = pd.DataFrame({
    "Business Insight": [
        f"{highest_revenue['RegionSegment']} generated the highest revenue.",
        f"{highest_cltv['RegionSegment']} achieved the highest Historical CLTV.",
        f"{lowest_revenue['RegionSegment']} generated the lowest revenue.",
        f"{highest_aov['RegionSegment']} recorded the highest Average Order Value.",
        f"{highest_pf['RegionSegment']} recorded the highest Purchase Frequency."
    ],

    "Business Impact": [
        "Revenue generation is concentrated in this region.",
        "Customers from this region generate greater long-term value.",
        "Additional marketing efforts are required to improve revenue.",
        "Customers spend more per transaction.",
        "Customers purchase more frequently in this region."
    ]
})

display(insights)

,Business Insight,Business Impact
0,UK generated the highest revenue.,Revenue generation is concentrated in this reg...
1,Other achieved the highest Historical CLTV.,Customers from this region generate greater lo...
2,Europe generated the lowest revenue.,Additional marketing efforts are required to i...
3,Other recorded the highest Average Order Value.,Customers spend more per transaction.
4,Other recorded the highest Purchase Frequency.,Customers purchase more frequently in this reg...

## Save Executive Business Insights

In [14]:
with pd.ExcelWriter("Executive_Business_Insights.xlsx") as writer:
    summary.to_excel(writer, sheet_name="Executive Summary", index=False)
    insights.to_excel(writer, sheet_name="Business Insights", index=False)
    recommendations_df = pd.DataFrame(recommendations, columns=["Recommendations"])
    recommendations_df.to_excel(writer, sheet_name="Recommendations", index=False)

print("Executive_Business_Insights.xlsx saved successfully.")

Executive_Business_Insights.xlsx saved successfully.